// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Mangaka.Migrations
{
    [DbContext(typeof(MiDbContext))]
    [Migration("20241021040255_SeedUserData1")]
    partial class SeedUserData1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Mangaka.Models.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("DateCreate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            DateCreate = new DateTime(2024, 10, 20, 23, 2, 54, 595, DateTimeKind.Local).AddTicks(5628),
                            Email = "eyder@gmail.com",
                            Name = "Eyder",
                            Password = "1234",
                            Status = true
                        },
                        new
                        {
                            ID = 2,
                            DateCreate = new DateTime(2024, 10, 20, 23, 2, 54, 595, DateTimeKind.Local).AddTicks(5643),
                            Email = "juan@gmail.com",
                            Name = "Juan",
                            Password = "5678",
                            Status = true
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
